### ISSUE TITLE
Not working in Android 10 

### ISSUE THREAD

**Issue by anshuman61** [NeutrinosPlatform/cordova-plugin-document-scanner#84] opened 2020-08-30 15:46 UTC
When we open scanner , and click picture after that app got hang and crashes 🥺🥺🥺🥺. Help Pls 🙏🙏🙏

**Comment by ChrisTomAlx** [comment] 2020-08-30 15:51
Duplicate of #74.

**Closed by ChrisTomAlx** 2020-08-30 15:51 UTC
