### ISSUE TITLE
Camera asking again 3 times after photo is clicked on rotate

### ISSUE THREAD

**Issue by Varun-garg** [NeutrinosPlatform/cordova-plugin-document-scanner#12] opened 2018-05-22 06:23 UTC
I am facing this issue when the phone is rotated during camera is already on. After saving the image it keeps asking again for like 3 times.

In the plugin, I tried adding the following line at beginning of `execute` and it didn't work.

    this.cordova.getActivity().setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);

And in Cordova project, following is already present, indicating the problem may be inside the `scanlibrary` used in this project.

    <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
        <intent-filter android:label="@string/launcher_name">
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
    </activity>

**Comment by ChrisTomAlx** [comment] 2018-05-22 08:37
I was able to reproduce this. Nice catch! I will look into this and get back to you as soon as possible.

**Comment by Varun-garg** [comment] 2018-05-24 06:18
This issue seems to be partially fixed, it doesn't ask again, but camera icon is always in portrait and images are always in landscape modes.

**Comment by ChrisTomAlx** [comment] 2018-05-28 05:49
The issue seems to be completely fixed for me after testing on S7 Edge. The camera and the scanned image are reacting to orientation change exactly as expected. Closing this issue for now. Let me know if you are having troubles with it still. If you are having problems please post a detailed description of the issue, since it will be hard to test on my side.

**Closed by ChrisTomAlx** 2018-05-28 05:49 UTC
Labels: bug

**Comment by ChrisTomAlx** [comment] 2018-06-05 10:20
@Varun-garg New Update fixes this issue completely. Just letting you know.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by Varun-garg** [comment] 2018-06-05 13:06
Hey chris, thanks a lot for fixing it. :smile:
