### ISSUE TITLE
Runtime Error: Failure delivering result ResultInfo

### ISSUE THREAD

**Issue by uzumakinaruto123** [NeutrinosPlatform/cordova-plugin-document-scanner#19] opened 2018-06-13 05:27 UTC
Facing Runtime error after adding the plugin.

`java.lang.RuntimeException: Failure delivering result ResultInfo{who=android:fragment:0, request=2, result=-1, data=null} to activity {custom.package.name/com.scanlibrary.ScanActivity}: java.lang.SecurityException: Failed to find provider  for user 0; expected to find a valid ContentProvider for this authority`

Once the picture is clicked and on clicking ok, app crashes with above error.

**Comment by ChrisTomAlx** [comment] 2018-06-13 05:32
Duplicate of issue #17.

Here is the solution :- 
Add `<preference name="android-targetSdkVersion" value="25" />` to your `config.xml` under platform android.

Closing this issue. If you need help please continue in issue #17

**Closed by ChrisTomAlx** 2018-06-13 05:32 UTC

**Comment by tulinisarg** [comment] 2018-06-13 05:33
Let's update the documentation with this information.

**Comment by ChrisTomAlx** [comment] 2018-06-13 05:36
@tulinisarg Will do.
