### ISSUE TITLE
Android 8

### ISSUE THREAD

**Issue by FaberDL89** [NeutrinosPlatform/cordova-plugin-document-scanner#30] opened 2018-08-10 13:56 UTC
Hi i have a problem for to release app with target api 26

**Comment by ChrisTomAlx** [comment] 2018-08-10 14:05
Hey @FaberDL89 ,

This issue has been clearly documented in the readme. Please consider going through the documentation before posting issues. Duplicate of issue #17.

Here is the hotfix solution you can use :-
Add <preference name="android-targetSdkVersion" value="25" /> to your config.xml under platform android.

Closing this issue. If you need help please continue in issue #17

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by FaberDL89** [comment] 2018-08-10 14:07
i can't becouse if i release on play store it want a app with android-targetSdkVersion 26

**Comment by FaberDL89** [comment] 2018-08-10 14:30
https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html

**Comment by ChrisTomAlx** [comment] 2018-08-13 06:05
@FaberDL89 
Oh. Will see what can be done about a permanent fix for this. Will let you know once I make some progress.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by muhammadsamir11** [comment] 2018-10-26 01:44
Hi @ChrisTomAlx any update about this issue
Thanks a lot

**Comment by ChrisTomAlx** [comment] 2018-10-26 08:57
Hey @muhammadsamir11 

I haven't yet tested on a real device but my colleague ran tests on an Android 8.0 Emulator successfully. Although I don't think that is enough. I will run tests on a real device as soon as I get my hands on one.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by ChrisTomAlx** [comment] 2018-12-20 17:09
Fixed and tested on Android 8+( Including 9 )

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Closed by ChrisTomAlx** 2018-12-20 17:09 UTC
